export const COMMERCIAL_SPECS: string[] = [
  "NY 2/3 SEMI WASHED 17/18 FINE CUP",
  "NY 2/3 SEMI WASHED 14/16 FINE CUP",
  "NATURAL NY 2/3 CERRADO/MOGIANA 17/18 FINE CUP",
  "NATURAL NY 2/3 CERRADO/MOGIANA 14/16 FINE CUP",
  "NATURAL NY 2/3 17/18 FINE CUP",
  "NATURAL NY 2/3 14/16 FINE CUP",
  "NATURAL PEABERRIES (MOKA) 9/10/11 FINE CUP",
  "NATURAL NY 2/3 17/18 GOOD CUP",
  "NATURAL NY 3/4 14/16 GOOD CUP",
  "NATURAL NY 5/6 GRINDERS 13UP GOOD CUP",
  "NATURAL NY 5/6 GRINDERS 12UP GOOD CUP",
  "RIO MINAS 17/18",
  "RIO MINAS 15/16",
  "RIO MINAS 14/16",
  "CONILON 13UP",
  "CONILON 14UP",
  "CONILON 16UP",
];

export const SEO_KEYWORDS: string[] = [
  "CazariniTrading",
  "Cazarini Trading",
  "Brazilian Green Coffee",
  "Green Coffee Varieties",
  "NY 2/3",
  "Semi Washed",
  "Fine Cup",
  "Good Cup",
  "Peaberries Moka",
  "Rio Minas",
  "Conilon",
  "Cerrado",
  "Mogiana",
  "17/18",
  "14/16",
  "13UP",
  "12UP",
];

